# Generated by Django 5.0.6 on 2024-11-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_parking_app', '0002_alter_bikerackdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='assessment_ids',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
